# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 03:32
from __future__ import unicode_literals

import apps.base_accounts.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.base_accounts.models.user_image_upload_to)),
                ('preferred_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], default=None, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Phone number')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_key', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('is_developer', models.BooleanField(default=False, help_text='User can see developer settings on the frontend clients.', verbose_name='Developer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
